export const containerBrandsStyles = {
  paddingTop: (theme) => theme.spacing(3),
  paddingBottom: (theme) => theme.spacing(3),
};

export const brandTitleStyles = {
  color: "white",
  textTransform: "uppercase",
  fontFamily: "Oswald, sans-serif",
  fontWeight: 500,
};

export const brandBoxesStyles = [
  {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "150px",
    background: "#00B4DB",
    background: "-webkit-linear-gradient(to right, #0083B0, #00B4DB)",
    background: "linear-gradient(to right, #1A1A1A, #888888)",
  },
  {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "150px",
    background: "#ED213A",
    background: "-webkit-linear-gradient(to right, #93291E, #ED213A)",
    background: "linear-gradient(to right, #93291E, #ED213A)",
  },
  {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "150px",
    background: "#cb2d3e",
    background: "-webkit-linear-gradient(to right, #ef473a, #cb2d3e)",
    background: "linear-gradient(to right, #ef473a, #cb2d3e)",
  },
  {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "150px",
    background: "#0575E6",
    background: "-webkit-linear-gradient(to right, #021B79, #0575E6)",
    background: "linear-gradient(to right, #021B79, #0575E6)",
  },
  {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "150px",
    background: "#005C97",
    background: "-webkit-linear-gradient(to right, #363795, #005C97)",
    background: "linear-gradient(to right, #363795, #005C97)",
  },
  {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "150px",
    background: "#FF512F",
    background: "-webkit-linear-gradient(to right,#FF512F,#F09819)",
    background: "linear-gradient(to right,#FF512F,#F09819)",
  },
  {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "150px",
    background: "#e52d27",
    background: "-webkit-linear-gradient(to right, #b31217, #e52d27)",
    background: "linear-gradient(to right, #b31217, #e52d27)",
  },
  {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "150px",
    background: "#00c6ff",
    background: "-webkit-linear-gradient(to right, #0072ff, #00c6ff)",
    background: "linear-gradient(to right, #0072ff, #00c6ff)",
  },
];
