export const ADD_STEP_STEPPER = 'ADD_STEP_STEPPER';
export const ADD_TO_CART = 'ADD_TO_CART';
export const CREATE_CART = 'CREATE_CART';
export const CLEAR_CART = "CLEAR_CART";
export const CLOSE_DRAWER = 'CLOSE_DRAWER';
export const FETCH_DATA_BRAND_PRODUCTS = 'FETCH_DATA_BRAND_PRODUCTS';
export const FETCH_DETAILS_PRODUCT = 'FETCH_DETAILS_PRODUCT';
export const OPEN_DRAWER = 'OPEN_DRAWER';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const SHOW_CART = 'SHOW_CART';
export const SHOW_CONTACT = 'SHOW_CONTACT';
export const SHOW_MENU = 'SHOW_MENU';
export const SHOW_SIGN_IN = 'SHOW_SIGN_IN';
export const SHOW_SIGN_UP = 'SHOW_SIGN_UP';
export const SHOW_FORGET_PASSWORD = 'SHOW_FORGET_PASSWORD';
export const TOGGLE_DARK_MODE = 'TOGGLE_DARK_MODE';
export const USER_DATA_CLEAR_PROFILE = 'USER_DATA_CLEAR_PROFILE';
export const USER_DATA_PROFILE = 'USER_DATA_PROFILE';
export const USER_LOGIN_DATA = 'USER_LOGIN_DATA';
export const UPDATE_ON_STOCK_CART_PRODUCT = 'UPDATE_ON_STOCK_CART_PRODUCT';
export const UPDATE_ON_STOCK_PRODUCT_DETAILS =
  'UPDATE_ON_STOCK_PRODUCT_DETAILS';
export const UPDATE_PRODUCTS_BRAND_ON_STOCK = 'UPDATE_PRODUCTS_BRAND_ON_STOCK';
export const UPDATE_RATE_PRODUCT_DETAILS = 'UPDATE_RATE_PRODUCT_DETAILS';
export const UPDATE_TOTAL_PRICE_CART_PRODUCT =
  'UPDATE_TOTAL_PRICE_CART_PRODUCT';
export const UPDATE_TOTAL_CART_AMOUNT = 'UPDATE_TOTAL_CART_AMOUNT';
export const UPDATE_TOTAL_CART_PRICE = 'UPDATE_TOTAL_CART_PRICE';
